on: [push]

jobs:
  container-build:
    runs-on: ubuntu-latest
    name: Build app container
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout local
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: decrypt secrets
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          openssl enc -d -aes-256-cbc -iter 20000 -pbkdf2 -in .github/workflows/secrets/id_ed25519.enc -out .github/workflows/secrets/id_ed25519 -k ${ENCRYPTION_KEY} 

      - name: setup SSH agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          chmod 0600 .github/workflows/secrets/id_ed25519
          ssh-add .github/workflows/secrets/id_ed25519

      - name: Checkout app
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git clone git@github.com:${{ github.repository }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        id: build
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          tags: ghcr.io/${{ github.repository}}:${{ github.sha }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: get output time
        run: echo "the time was ${{ steps.build.time }}"
